context:
    cache: true
contextmaps:
  - prefix: "https://schema.org/"
    file: "/assets/schemaorg-current-https.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
  - prefix: "http://schema.org/"
    file: "/assets/schemaorg-current-http.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
gleaner:
    mill: true
    runid: runX
    summon: true
millers:
    graph: true
minio:
    address:
    port: 443
    ssl: true
    bucket: ecrr
    region:
    accesskey:
    secretkey:
sources:
    - sourcetype: googledrive
      name: ecrr_submitted
      logo: https://www.earthcube.org/sites/default/files/doc-repository/logo_earthcube_full_horizontal.png
      url: https://drive.google.com/drive/u/0/folders/1TacUQqjpBbGsPQ8JPps47lBXMQsNBRnd
      headless: false
      pid: ""
      propername: Earthcube Resource Registry
      domain: http://www.earthcube.org/resourceregistry/
      active: true
      credentialsfile: configs/credentials/gleaner-331805-030e15e1d9c4.json
      other: {}
      headlesswait: 0
      delay: 0
      identifierpath: ""
      apipagelimit: 0
      identifiertype: identifierstring
      fixcontextoption: 0
      acceptcontenttype: application/ld+json, text/html
      jsonprofile: application/ld+json
    - sourcetype: sitemap
      name: ecrr_examples
      logo: https://www.earthcube.org/sites/default/files/doc-repository/logo_earthcube_full_horizontal.png
      url: https://raw.githubusercontent.com/earthcube/ecrro/gh-pages/Examples/sitemap.xml
      headless: false
      pid: ""
      propername: Earthcube Resource Registry Examples
      domain: http://www.earthcube.org/resourceregistry/examples
      active: false
      credentialsfile: ""
      other: {}
      headlesswait: 0
      delay: 0
      identifierpath: ""
      apipagelimit: 0
      identifiertype: identifierstring
      fixcontextoption: 0
      acceptcontenttype: application/ld+json, text/html
      jsonprofile: application/ld+json
#    - sourcetype: s3
#      name: ecrr_form
#      logo: ""
#      url: https://oss.geocodes.earthcube.org/ecrr/
#      headless: false
#      pid: ""
#      propername: New Earthcube Resource Registry
#      domain: http://www.earthcube.org/resourceregistry/
#      active: false
#      credentialsfile: ""
#      other: {}
#      headlesswait: 0
#      delay: 0
#      identifierpath: ""
#      apipagelimit: 0
#      identifiertype: identifierstring
#      fixcontextoption: 0
#      acceptcontenttype: application/ld+json, text/html
#      jsonprofile: application/ld+json
#    - sourcetype: s3
#      name: forms_ecrr
#      logo: ""
#      url: https://oss.geocodes.earthcube.org/forms
#      headless: false
#      pid: ""
#      propername: New ECRR forms
#      domain: ""
#      active: false
#      credentialsfile: ""
#      other: {}
#      headlesswait: 0
#      delay: 0
#      identifierpath: ""
#      apipagelimit: 0
#      identifiertype: identifierstring
#      fixcontextoption: 0
#      acceptcontenttype: application/ld+json, text/html
#      jsonprofile: application/ld+json
summoner:
    after: ""
    delay: null
    headless: http://127.0.0.1:9222
    mode: full
    threads: 5
