minio:
  bucket:
  address:
  port:
  accesskey:
  secretkey:
  ssl: true
context:
    cache: true
    strict: true
contextmaps:
  - prefix: "https://schema.org/"
    file: "/assets/schemaorg-current-https.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
  - prefix: "http://schema.org/"
    file: "/assets/schemaorg-current-http.jsonld"  # wget http://schema.org/docs/jsonldcontext.jsonld
sparql:
  endpoint:
objects:
  domain: us-east-1
  prefix:
    - summoned/aquadocs
    - summoned/bcodmo
    - summoned/cchdo
    - summoned/earthchem
    - summoned/edi
    - summoned/hydroshare
    - summoned/linkedearth
    - summoned/magic
    - summoned/opentopography
    - summoned/r2r
    - summoned/ssdbiodp
    - summoned/unavco
    - prov/aquadocs
    - prov/bcodmo
    - prov/cchdo
    - prov/earthchem
    - prov/edi
    - prov/hydroshare
    - prov/linkedearth
    - prov/magic
    - prov/opentopography
    - prov/r2r
    - prov/ssdbiodp
    - prov/unavco


